/**
 * Entity JSON Suite — Node.js serving layer.
 *
 * Serves static JSON files generated by:
 *   - headless_entity_serializer (entity files)
 *   - entity_json_views (view files)
 *   - AliasBucketManager (alias mappings)
 *
 * Routes:
 *   GET /json/:type/:id/:lang         — single entity translation
 *   GET /json/views/:view/:display    — view export
 *   GET /json/path/:alias             — alias → entity translation
 *
 * Configuration via .env (see .env.example).
 */

import Fastify from 'fastify';
import cors from '@fastify/cors';
import { config } from './config.js';
import entityRoutes from './routes/entity.js';
import viewRoutes from './routes/view.js';
import aliasRoutes from './routes/alias.js';

const fastify = Fastify({
  logger: { level: config.log.level },
});

await fastify.register(cors, {
  origin: config.cors.origin,
});

await fastify.register(entityRoutes, config);
await fastify.register(viewRoutes, config);
await fastify.register(aliasRoutes, config);

fastify.get('/health', async () => ({ status: 'ok' }));

try {
  await fastify.listen({ port: config.port, host: config.host });
}
catch (err) {
  fastify.log.error(err);
  process.exit(1);
}
