<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function entity_json_speed_entity_insert(EntityInterface $entity) {
  \Drupal::service("entity_json_speed.global_entities")->export($entity);
  \Drupal::service("entity_json_speed.alias")->export($entity);
}

/**
 * Implements hook_entity_update().
 */
function entity_json_speed_entity_update(EntityInterface $entity) {
    \Drupal::service("entity_json_speed.global_entities")->export($entity);
  \Drupal::service("entity_json_speed.alias")->export($entity);
}

/**
 * Implements hook_entity_translation_delete().
 *
 * Deletes the entity cache when a translation of an entity is deleted.
 *
 * @param \Drupal\Core\Entity\EntityInterface $translation
 *   The translation entity that was deleted.
 */
function entity_json_speed_entity_translation_delete(EntityInterface $translation) {
  \Drupal::service("entity_json_speed.global_entities")->delete($translation);
  \Drupal::service("entity_json_speed.alias")->delete($translation);
}


/**
 * Implements hook_entity_delete().
 */
function entity_json_speed_entity_delete(EntityInterface $entity) {
  \Drupal::service("entity_json_speed.global_entities")->delete($entity);
  \Drupal::service("entity_json_speed.alias")->delete($entity);
}


function entity_json_speed_preprocess_html($variables) {

/*
  $node = \Drupal::entityTypeManager()->getStorage('node')->load(1695);
  dump($node);

  $path_alias = \Drupal::entityTypeManager()
  ->getStorage('path_alias')
  ->loadByProperties(['path' => "/node/1695"]);
  $path_alias = reset($path_alias);


  dump($path_alias);

  $alias = \Drupal::service("entity_json_speed.alias")->getPathAliasEntityByEntity($node);
  dump($alias);*/

  /*$ejsf = \Drupal::service("entity_json_speed.file");
  dump($ejsf->getPathsFilesEntity($node));

  $is_original = $node->isDefaultTranslation();
  dump($is_original); */
}


