<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function entity_json_speed_entity_insert(EntityInterface $entity) {
  \Drupal::service("entity_json_speed.global_entities")->export($entity);
  \Drupal::service("entity_json_speed.alias")->export($entity);


}

/**
 * Implements hook_entity_update().
 */
function entity_json_speed_entity_update(EntityInterface $entity) {
    \Drupal::service("entity_json_speed.global_entities")->export($entity);
    \Drupal::service("entity_json_speed.alias")->export($entity);

}

/**
 * Implements hook_entity_delete().
 */
function entity_json_speed_entity_delete(EntityInterface $entity) {
  \Drupal::service("entity_json_speed.global_entities")->delete($entity);
  \Drupal::service("entity_json_speed.alias")->delete($entity);
}


